#!/bin/sh

##############################################################################
#
# Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

app_path=$0
while [ -h "$app_path" ]; do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
      /*) app_path=$link ;;
      *)  app_path=$( dirname "$app_path" )/$link ;;
    esac
done

APP_HOME=$( cd "${app_path%/*}/" && pwd -P ) || exit
APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
DEFAULT_JVM_OPTS='-Xmx64m -Xms64m'

if [ -z "${JAVA_HOME}" ]; then
    JAVACMD=java
    which java >/dev/null 2>&1 || die "JAVA_HOME is not set and no 'java' command could be found in your PATH."
else
    JAVACMD="$JAVA_HOME/bin/java"
    [ -x "$JAVACMD" ] || die "JAVA_HOME is set to an invalid directory: $JAVA_HOME"
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
